// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package db

import (
	"context"
)

const getQueryByName = `-- name: GetQueryByName :one
SELECT id, name, query FROM queries
WHERE "name" = $1
`

func (q *Queries) GetQueryByName(ctx context.Context, name string) (Query, error) {
	row := q.db.QueryRowContext(ctx, getQueryByName, name)
	var i Query
	err := row.Scan(&i.ID, &i.Name, &i.Query)
	return i, err
}
