// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: rpc_add_email.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddEmailAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonId uint64 `protobuf:"varint,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *AddEmailAddressRequest) Reset() {
	*x = AddEmailAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_add_email_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmailAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmailAddressRequest) ProtoMessage() {}

func (x *AddEmailAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_email_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmailAddressRequest.ProtoReflect.Descriptor instead.
func (*AddEmailAddressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_add_email_proto_rawDescGZIP(), []int{0}
}

func (x *AddEmailAddressRequest) GetPersonId() uint64 {
	if x != nil {
		return x.PersonId
	}
	return 0
}

func (x *AddEmailAddressRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AddEmailAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *EmailAddress `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *AddEmailAddressResponse) Reset() {
	*x = AddEmailAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_add_email_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmailAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmailAddressResponse) ProtoMessage() {}

func (x *AddEmailAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_email_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmailAddressResponse.ProtoReflect.Descriptor instead.
func (*AddEmailAddressResponse) Descriptor() ([]byte, []int) {
	return file_rpc_add_email_proto_rawDescGZIP(), []int{1}
}

func (x *AddEmailAddressResponse) GetEmail() *EmailAddress {
	if x != nil {
		return x.Email
	}
	return nil
}

var File_rpc_add_email_proto protoreflect.FileDescriptor

var file_rpc_add_email_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d,
	0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x3a, 0x40, 0x92, 0x41,
	0x3d, 0x0a, 0x3b, 0x2a, 0x10, 0x41, 0x64, 0x64, 0x20, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x13, 0x41, 0x64, 0x64, 0x20, 0x61, 0x6e, 0x20, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0xd2, 0x01, 0x09, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0xd2, 0x01, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x81,
	0x01, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x03, 0x92, 0x41, 0x00,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x3a, 0x39, 0x92, 0x41, 0x36, 0x0a, 0x34, 0x2a, 0x12,
	0x41, 0x64, 0x64, 0x65, 0x64, 0x20, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x32, 0x1e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x20, 0x74, 0x68, 0x65, 0x20,
	0x61, 0x64, 0x64, 0x65, 0x64, 0x20, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x69, 0x74, 0x73, 0x73, 0x63, 0x62, 0x2f, 0x64, 0x66, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_add_email_proto_rawDescOnce sync.Once
	file_rpc_add_email_proto_rawDescData = file_rpc_add_email_proto_rawDesc
)

func file_rpc_add_email_proto_rawDescGZIP() []byte {
	file_rpc_add_email_proto_rawDescOnce.Do(func() {
		file_rpc_add_email_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_add_email_proto_rawDescData)
	})
	return file_rpc_add_email_proto_rawDescData
}

var file_rpc_add_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_add_email_proto_goTypes = []interface{}{
	(*AddEmailAddressRequest)(nil),  // 0: pb.AddEmailAddressRequest
	(*AddEmailAddressResponse)(nil), // 1: pb.AddEmailAddressResponse
	(*EmailAddress)(nil),            // 2: pb.EmailAddress
}
var file_rpc_add_email_proto_depIdxs = []int32{
	2, // 0: pb.AddEmailAddressResponse.email:type_name -> pb.EmailAddress
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_add_email_proto_init() }
func file_rpc_add_email_proto_init() {
	if File_rpc_add_email_proto != nil {
		return
	}
	file_email_address_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_add_email_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmailAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_add_email_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmailAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_add_email_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_add_email_proto_goTypes,
		DependencyIndexes: file_rpc_add_email_proto_depIdxs,
		MessageInfos:      file_rpc_add_email_proto_msgTypes,
	}.Build()
	File_rpc_add_email_proto = out.File
	file_rpc_add_email_proto_rawDesc = nil
	file_rpc_add_email_proto_goTypes = nil
	file_rpc_add_email_proto_depIdxs = nil
}
