DROP TABLE IF EXISTS "returnsLog";
DROP TABLE IF EXISTS "returns";
DROP TABLE IF EXISTS "payments";
DROP TABLE IF EXISTS "documents";
DROP TABLE IF EXISTS "mails";
DROP TABLE IF EXISTS "persons";
DROP TABLE IF EXISTS "providers";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "account_info";
DROP TABLE IF EXISTS "accounts";








